"""Q3b — Kill-criteria research log report."""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CSV = ROOT / "kill_log.csv"
OUT = ROOT / "kill_report.html"


def main() -> None:
    rows = list(csv.DictReader(CSV.open(encoding="utf-8")))
    active = [r for r in rows if not r.get("killed")]
    killed = [r for r in rows if r.get("killed")]
    tr = "".join(
        f"<tr><td>{r['idea_id']}</td><td>{r['started']}</td><td>{r['killed'] or '—'}</td>"
        f"<td>{r['trigger']}</td><td>{r['status']}</td><td>{r['hypothesis']}</td>"
        f"<td>{r['what_we_learned']}</td></tr>"
        for r in rows
    )
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"/><title>Kill criteria log</title>
<style>
body{{font-family:system-ui;background:#0c1117;color:#e8eef5;padding:2rem}}
table{{border-collapse:collapse;width:100%;font-size:0.9rem}}
th,td{{border:1px solid #2a3542;padding:0.5rem;text-align:left;vertical-align:top}}
th{{background:#151c25}}
.muted{{color:#9aa7b5}}
</style></head><body>
<h1>Kill-criteria research log</h1>
<p class="muted">Ideas: {len(rows)} · Active/paused: {len(active)} · Killed: {len(killed)}</p>
<table>
<thead><tr><th>ID</th><th>Started</th><th>Killed</th><th>Trigger</th><th>Status</th><th>Hypothesis</th><th>Learned</th></tr></thead>
<tbody>{tr}</tbody>
</table>
<p class="muted">Generated by run_kill_log.py — illustrative until replaced with live archive.</p>
</body></html>
"""
    OUT.write_text(html, encoding="utf-8")
    print(f"Ideas: {len(rows)} | active/paused: {len(active)} | killed: {len(killed)}")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
